// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyStreamHistory.ViewerService.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyStreamHistory.ViewerService.Infrastructure.Migrations
{
    [DbContext(typeof(ViewerServiceDbContext))]
    [Migration("20260212090710_AddViewerStatsAndExperience")]
    partial class AddViewerStatsAndExperience
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyStreamHistory.ViewerService.Domain.Entities.ProcessedEventSubMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("ProcessedAt");

                    b.ToTable("ProcessedEventSubMessages");
                });

            modelBuilder.Entity("MyStreamHistory.ViewerService.Domain.Entities.Viewer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastDataSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TwitchUserId")
                        .IsUnique();

                    b.ToTable("Viewers");
                });

            modelBuilder.Entity("MyStreamHistory.ViewerService.Domain.Entities.ViewerCategoryWatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ChatPoints")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Experience")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MinutesWatched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("StreamCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ViewerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StreamCategoryId");

                    b.HasIndex("ViewerId");

                    b.HasIndex("ViewerId", "StreamCategoryId")
                        .IsUnique();

                    b.ToTable("ViewerCategoryWatches");
                });

            modelBuilder.Entity("MyStreamHistory.ViewerService.Domain.Entities.ViewerStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("EarnedMsgPoints")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Experience")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MinutesWatched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("StreamerTwitchUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ViewerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StreamerTwitchUserId");

                    b.HasIndex("ViewerId");

                    b.HasIndex("StreamerTwitchUserId", "Experience");

                    b.HasIndex("ViewerId", "StreamerTwitchUserId")
                        .IsUnique();

                    b.ToTable("ViewerStats");
                });

            modelBuilder.Entity("MyStreamHistory.ViewerService.Domain.Entities.ViewerCategoryWatch", b =>
                {
                    b.HasOne("MyStreamHistory.ViewerService.Domain.Entities.Viewer", "Viewer")
                        .WithMany("CategoryWatches")
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("MyStreamHistory.ViewerService.Domain.Entities.ViewerStats", b =>
                {
                    b.HasOne("MyStreamHistory.ViewerService.Domain.Entities.Viewer", "Viewer")
                        .WithMany("Stats")
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("MyStreamHistory.ViewerService.Domain.Entities.Viewer", b =>
                {
                    b.Navigation("CategoryWatches");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
