services:
  mystreamhistoryweb:
    container_name: mystreamhistorywebcontainer
    build: .
    image: mystreamhistoryweb
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    networks:
      - internalnet
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    environment:
      - NGINX_HOST=mystreamhistory.com
      - NGINX_PORT=443
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot -d mystreamhistory.com

networks:
  internalnet:
    driver: bridge