services:
  mystreamhistoryweb:
    container_name: mystreamhistorywebcontainer
    build: .
    image: mystreamhistoryweb
    ports:
      - "80:80"
    expose:
      - "80"
    networks:
      - internalnet
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    environment:
      - NGINX_HOST=mystreamhistory.com
      - NGINX_PORT=80
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot -d mystreamhistory.com --email your-email@example.com --agree-tos --non-interactive

networks:
  internalnet:
    driver: bridge
