version: '3.4'

services:
  mystreamhistory.api:
    image: mystreamhistoryapi
    container_name: mystreamhistory.api
    build:
      context: /var/www/mystreamhistory
      dockerfile: MyStreamHistory.API/Dockerfile
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MY_DB_CONNECTION_STRING=${MY_DB_CONNECTION_STRING}
    expose:
      - "5000"
      - "5001"

  mystreamhistory.database:
    image: postgres:latest
    container_name: mystreamhistory.database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /var/www/mystreamhistory/.containers/mystreamhistory-db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  mystreamhistory.migrations:
    image: mystreamhistoryapi
    container_name: mystreamhistory.migrations
    build:
      context: /var/www/mystreamhistory
      dockerfile: MyStreamHistory.API/Dockerfile
    command: ["dotnet", "ef", "database", "update", "--environment", "Production"]
    depends_on:
      - mystreamhistory.database

  mystreamhistory.nginx:
    image: nginx:latest
    container_name: mystreamhistory.nginx
    depends_on:
      - mystreamhistory.api
    volumes:
      - /var/www/mystreamhistory/MyStreamHistory.API/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
