// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyStreamHistory.TwitchTrackingService.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyStreamHistory.TwitchTrackingService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TwitchTrackingDbContext))]
    partial class TwitchTrackingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyStreamHistory.TwitchTrackingService.Domain.Entities.EventSubSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TwitchSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TwitchUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TwitchSubscriptionId")
                        .IsUnique();

                    b.HasIndex("TwitchUserId");

                    b.ToTable("EventSubSubscriptions");
                });

            modelBuilder.Entity("MyStreamHistory.TwitchTrackingService.Domain.Entities.StreamCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StreamSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TwitchCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TwitchCategoryId");

                    b.HasIndex("StreamSessionId", "EndedAt");

                    b.HasIndex("StreamSessionId", "StartedAt");

                    b.ToTable("StreamCategories");
                });

            modelBuilder.Entity("MyStreamHistory.TwitchTrackingService.Domain.Entities.StreamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StreamId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StreamTitle")
                        .HasColumnType("text");

                    b.Property<string>("StreamerAvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("StreamerDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StreamerLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TwitchUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("ViewerCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsLive");

                    b.HasIndex("StreamId");

                    b.HasIndex("TwitchUserId");

                    b.ToTable("StreamSessions");
                });

            modelBuilder.Entity("MyStreamHistory.TwitchTrackingService.Domain.Entities.TwitchCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BoxArtUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IgdbId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TwitchId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TwitchId")
                        .IsUnique();

                    b.ToTable("TwitchCategories");
                });

            modelBuilder.Entity("MyStreamHistory.TwitchTrackingService.Domain.Entities.StreamCategory", b =>
                {
                    b.HasOne("MyStreamHistory.TwitchTrackingService.Domain.Entities.StreamSession", "StreamSession")
                        .WithMany("StreamCategories")
                        .HasForeignKey("StreamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyStreamHistory.TwitchTrackingService.Domain.Entities.TwitchCategory", "TwitchCategory")
                        .WithMany("StreamCategories")
                        .HasForeignKey("TwitchCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamSession");

                    b.Navigation("TwitchCategory");
                });

            modelBuilder.Entity("MyStreamHistory.TwitchTrackingService.Domain.Entities.StreamSession", b =>
                {
                    b.Navigation("StreamCategories");
                });

            modelBuilder.Entity("MyStreamHistory.TwitchTrackingService.Domain.Entities.TwitchCategory", b =>
                {
                    b.Navigation("StreamCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
