// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyStreamHistory.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyStreamHistory.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250701102510_AddedCoreModels")]
    partial class AddedCoreModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyStreamHistory.API.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Checksum")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("IgdbId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IgdbId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("MyStreamHistory.API.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MyStreamHistory.API.Models.Stream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Finished")
                        .HasColumnType("boolean");

                    b.Property<int>("StreamId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("WithInfoAboutViewers")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Streams");
                });

            modelBuilder.Entity("MyStreamHistory.API.Models.TwitchCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoxArtUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TwitchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TwitchId")
                        .IsUnique();

                    b.ToTable("TwitchCategories");
                });

            modelBuilder.Entity("MyStreamHistory.API.Models.TwitchCategoryOnStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("StreamId")
                        .HasColumnType("integer");

                    b.Property<int>("TwitchCategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StreamId");

                    b.HasIndex("TwitchCategoryId");

                    b.ToTable("TwitchCategoriesOnStream");
                });

            modelBuilder.Entity("MyStreamHistory.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("BroadcasterType")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool?>("FreshToken")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsStreamer")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUser")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("SiteCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TwitchCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TwitchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TwitchId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyStreamHistory.API.Models.Viewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BroadcasterType")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUser")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TwitchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TwitchId")
                        .IsUnique();

                    b.ToTable("Viewers");
                });

            modelBuilder.Entity("MyStreamHistory.API.Models.ViewerPerTwitchCategoryOnStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EarnedMsgPoints")
                        .HasColumnType("numeric");

                    b.Property<int>("TwitchCategoryOnStreamId")
                        .HasColumnType("integer");

                    b.Property<int>("ViewerId")
                        .HasColumnType("integer");

                    b.Property<int>("WatchedMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TwitchCategoryOnStreamId");

                    b.HasIndex("ViewerId");

                    b.ToTable("ViewersPerTwitchCategoryOnStream");
                });

            modelBuilder.Entity("MyStreamHistory.API.Models.RefreshToken", b =>
                {
                    b.HasOne("MyStreamHistory.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyStreamHistory.API.Models.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyStreamHistory.API.Models.Stream", b =>
                {
                    b.HasOne("MyStreamHistory.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyStreamHistory.API.Models.TwitchCategoryOnStream", b =>
                {
                    b.HasOne("MyStreamHistory.API.Models.Stream", "Stream")
                        .WithMany("CategoriesOnStream")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyStreamHistory.API.Models.TwitchCategory", "Category")
                        .WithMany("CategoriesOnStream")
                        .HasForeignKey("TwitchCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("MyStreamHistory.API.Models.ViewerPerTwitchCategoryOnStream", b =>
                {
                    b.HasOne("MyStreamHistory.API.Models.TwitchCategoryOnStream", "TwitchCategoryOnStream")
                        .WithMany("Viewers")
                        .HasForeignKey("TwitchCategoryOnStreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyStreamHistory.API.Models.Viewer", "Viewer")
                        .WithMany("ViewerPerTwitchCategoriesOnStream")
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TwitchCategoryOnStream");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("MyStreamHistory.API.Models.Stream", b =>
                {
                    b.Navigation("CategoriesOnStream");
                });

            modelBuilder.Entity("MyStreamHistory.API.Models.TwitchCategory", b =>
                {
                    b.Navigation("CategoriesOnStream");
                });

            modelBuilder.Entity("MyStreamHistory.API.Models.TwitchCategoryOnStream", b =>
                {
                    b.Navigation("Viewers");
                });

            modelBuilder.Entity("MyStreamHistory.API.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("MyStreamHistory.API.Models.Viewer", b =>
                {
                    b.Navigation("ViewerPerTwitchCategoriesOnStream");
                });
#pragma warning restore 612, 618
        }
    }
}
